### ISSUE TITLE
ADVANCED+sourcemaps fails on windows (jszip path?)

### ISSUE THREAD

**Issue by xamde** [Vertispan/j2clmavenplugin#135]
The error materializes when 
```
<compilationLevel>ADVANCED</compilationLevel>
<enableSourcemaps>true</enableSourcemaps>
```
and we get the same results for WHITESPACE_ONLY with sourcemaps.

Results:
```
java.lang.NullPointerException: C:\Users\xamde\.m2\repository\com\vertispan\j2cl\jre\0.10-SNAPSHOT\jre-0.10-SNAPSHOT-jszip.zip!/java\io\HasSerializableTypeMarker$$Overlay.js.map
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1243)
        at com.google.javascript.jscomp.JSCompZipFileCache$CachedZipFile.getEntryStream(JSCompZipFileCache.java:88)
        at com.google.javascript.jscomp.JSCompZipFileCache.getEntryStream(JSCompZipFileCache.java:52)
        at com.google.javascript.jscomp.SourceFile$CodeLoader$AtZip.openUncachedReader(SourceFile.java:790)
        at com.google.javascript.jscomp.SourceFile$CodeLoader$AtZip.loadUncachedCode(SourceFile.java:783)
        at com.google.javascript.jscomp.SourceFile.getCode(SourceFile.java:155)
        at com.google.javascript.jscomp.SourceMapInput.getSourceMap(SourceMapInput.java:56)
        at com.google.javascript.jscomp.Compiler.getSourceMapping(Compiler.java:3013)
        at com.google.javascript.jscomp.SourceMap.addMapping(SourceMap.java:175)
        at com.google.javascript.jscomp.CodePrinter$MappedCodePrinter.generateSourceMap(CodePrinter.java:155)
        at com.google.javascript.jscomp.CodePrinter.toSource(CodePrinter.java:845)
        at com.google.javascript.jscomp.CodePrinter.access$300(CodePrinter.java:42)
        at com.google.javascript.jscomp.CodePrinter$Builder.build(CodePrinter.java:774)
        at com.google.javascript.jscomp.Compiler.toSource(Compiler.java:2451)
        at com.google.javascript.jscomp.Compiler.lambda$toSource$24(Compiler.java:2418)
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:127)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:1010)
        at com.google.javascript.jscomp.Compiler.toSource(Compiler.java:2380)
        at com.google.javascript.jscomp.Compiler.lambda$toSource$22(Compiler.java:2342)
        at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] Exception executing task de.xam.example.app:client-app:0.1.0-SNAPSHOT/optimized_js
java.lang.IllegalStateException: Closure Compiler failed, check log for details
    at com.vertispan.j2cl.build.provided.ClosureTask$4.execute (ClosureTask.java:245)
    at com.vertispan.j2cl.build.TaskScheduler$2.executeTask (TaskScheduler.java:172)
    at com.vertispan.j2cl.build.TaskScheduler$2.lambda$onReady$0 (TaskScheduler.java:211)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:304)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
java.lang.RuntimeException
        at com.vertispan.j2cl.build.DiskCache.markFailed(DiskCache.java:452)
        at com.vertispan.j2cl.build.DiskCache$CacheResult.markFailure(DiskCache.java:54)
        at com.vertispan.j2cl.build.TaskScheduler$2.executeTask(TaskScheduler.java:181)
        at com.vertispan.j2cl.build.TaskScheduler$2.lambda$onReady$0(TaskScheduler.java:211)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

Closure log ends with
```
[DEBUG] --js_output_file
[DEBUG] C:\_data_\_p_\_git\GitHub\j2cl-super\client-app\target\gwt3BuildCache\0.19-SNAPSHOT\de.xam.example.app-client-app-0.1.0-SNAPSHOT\defbf801897a391a6846ed44ff33cfcc-optimized_js\results/client-app/client-app.js
[DEBUG] --env
[DEBUG] BROWSER
[INFO]  0 error(s), 0 warning(s), 95,5% typed
```

**Comment by niloc132** [comment]
If you get the chance, could you try this again with 0.20-SNAPSHOT? We've swapped out jszip on that branch in favor of unpacking zips in order to get better compatibility with other features of closure that don't support zips.
