### ISSUE TITLE
ConcurrentModificationException on newer JREs

### ISSUE THREAD

**Issue by niloc132** [Vertispan/j2clmavenplugin#18]
See #6 for earlier discussion, candidate fix that doesn't work.

In Java 9 and above, the plugin throws a ConcurrentModificationException on many projects when building:
```
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)
        at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2671)
        at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:224)
        at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:296)
        at net.cardosi.mojo.cache.CachedProject.jscompWithScope(CachedProject.java:322)
        at net.cardosi.mojo.cache.CachedProject.registerAsApp(CachedProject.java:212)
        at net.cardosi.mojo.BuildMojo.execute(BuildMojo.java:131)
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

Switching to ConcurrentHashMap just changes the issue on some projects, now it deadlocks in some conditions:
```
"main" #1 prio=5 os_prio=0 tid=0x00007f81ec00a800 nid=0x14c54 runnable [0x00007f81f36c9000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1718)
	at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:221)
	at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:293)
	at net.cardosi.mojo.cache.CachedProject.hash(CachedProject.java:687)
	at net.cardosi.mojo.cache.CachedProject.lambda$getOrCreate$5(CachedProject.java:226)
	at net.cardosi.mojo.cache.CachedProject$$Lambda$16/1306067302.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	- locked <0x0000000720a18db8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:221)
	at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:293)
	at net.cardosi.mojo.cache.CachedProject.jscompWithScope(CachedProject.java:319)
	at net.cardosi.mojo.cache.CachedProject.registerAsApp(CachedProject.java:209)
	at net.cardosi.mojo.WatchMojo.execute(WatchMojo.java:135)
```

Best workaround for the moment: use Java 8.

**Comment by niloc132** [comment]
Please note that the fix for this also required a change to the pom to exclude the error-prone java compiler jar, provided by @mp1. This is probably going to bite us someday, as this dependency is necessary in order to use the JAVAC frontend instead of JDT in j2cl, and eventually jdt is going to be outright phased out.

**Comment by mP1** [comment]
Yes the real problem is the way ConcurrentHashMap.putIfAbsent is being used is "incompatible" with the contract and for whatever reason jre9 changed or became more strict about this.

**Comment by niloc132** [comment]
With the updated code, the change in map isnt actually necessary - we're just avoiding a hash collision or something (probably not actual collision of hash, but of which bucket it is in, something like that) in the put-in-a-put operation. The `Hash` operation is special in this way, so the _real_ fix here is to compute all hashes in the dependency tree up front. 

Making the change from one map to the other only appears to fix the issue - the "collision" can still happen, but instead of happening every time, it only happens on some projects.
