### ISSUE TITLE
Exception on watch mode while adding new class

### ISSUE THREAD

**Issue by vegegoku** [Vertispan/j2clmavenplugin#32]
Steps to reproduce

run `mvn j2cl:watch`

then try to add a new class
start adding new fields to the new class and check the logs for watch mode

it will throw an exception

```
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at com.google.javascript.jscomp.CommandLineRunner$Flags.getMixedJsSources(CommandLineRunner.java:1192)
        at com.google.javascript.jscomp.CommandLineRunner.initConfigFromFlags(CommandLineRunner.java:1593)
        at com.google.javascript.jscomp.CommandLineRunner.<init>(CommandLineRunner.java:1438)
        at net.cardosi.mojo.tools.Closure$InProcessJsCompRunner.<init>(Closure.java:113)
        at net.cardosi.mojo.tools.Closure.compile(Closure.java:82)
        at net.cardosi.mojo.cache.CachedProject.lambda$jscompWithScope$13(CachedProject.java:380)
        at net.cardosi.mojo.cache.CachedProject.lambda$null$7(CachedProject.java:306)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
done with pool work for org.dominokit.samples:mvpj2cl-frontend:1.0-SNAPSHOT AssembleOutput-fb17109caa178edd936e0cab76dff741144b5500 in 1861ms
failed org.dominokit.samples:mvpj2cl-frontend:1.0-SNAPSHOT AssembleOutput-fb17109caa178edd936e0cab76dff741144b5500 class java.util.concurrent.CompletionException:java.util.ConcurrentModificationException
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at com.google.javascript.jscomp.CommandLineRunner$Flags.getMixedJsSources(CommandLineRunner.java:1192)
        at com.google.javascript.jscomp.CommandLineRunner.initConfigFromFlags(CommandLineRunner.java:1593)
        at com.google.javascript.jscomp.CommandLineRunner.<init>(CommandLineRunner.java:1438)
        at net.cardosi.mojo.tools.Closure$InProcessJsCompRunner.<init>(Closure.java:113)
        at net.cardosi.mojo.tools.Closure.compile(Closure.java:82)
        at net.cardosi.mojo.cache.CachedProject.lambda$jscompWithScope$13(CachedProject.java:380)
        at net.cardosi.mojo.cache.CachedProject.lambda$null$7(CachedProject.java:306)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
        ... 5 more

```

**Comment by niloc132** [comment]
Thanks - we used to have some mitigation around this by forcing old builds to stop before kicking off the next round, but that seems to not be working now? We are reusing the compiler instance i believe, and I'm guessing that is where this comodification is taking place.

**Comment by vegegoku** [comment]
i am not sure if it is related, but also while the watch mode is active the IDE keeps hanging for a split second or less, but you can feel it.

**Comment by niloc132** [comment]
Hard to say - it might be watching the filesystem changes that j2cl-maven-plugin is making and reindexing? are you using a global cache dir?

**Comment by vegegoku** [comment]
I left it to the default, so i think it is in the target folder

**Comment by niloc132** [comment]
We have to expect that users will do this and support it somehow, but at the same time it would be nice to tell intellij to cut it out, leave that dir alone... I wonder if we used zip files instead of directories if that would be cleaner for IJ, especially since j2cl can natively support this (at this time).

**Comment by niloc132** [comment]
Finally revisiting this, it appears that it isn't safe to run multiple copies of the closure Compiler in the same JVM (or at least the same classloader), unless you guarantee they have the same args passed to them, and beyond that, not even set the args the second+ time. This may mean that it isn't possible to even build BUNDLE_JAR output in parallel with itself, or "cancel" a build job without also waiting for it to entirely die before starting a more correct one.

Best case I can see at the moment is that we might get away with serializing the arg initialization, but I'll need to chase down more usages of these fields to ensure that this is sufficient. 

Current version of code which must not be shared across threads: https://github.com/google/closure-compiler/blob/8c82325/src/com/google/javascript/jscomp/CommandLineRunner.java#L144-L150

Comment added: https://github.com/google/closure-compiler/commit/ace3da387f8a7d5ca342fd49b9fb8990f43be38f

I'll do some more reading and try a candidate fix if this bears out, maybe you can try it.

**Comment by niloc132** [comment]
@vegegoku when time permits, try latest 0.15 builds to see if this bug is gone.
