### ISSUE TITLE
To many open files when compiling dominodo sample twice

### ISSUE THREAD

**Issue by vegegoku** [Vertispan/j2clmavenplugin#34]
```
done with pool work for org.dominokit.samples:dominodo-j2cl:1.0-SNAPSHOT StripGwtIncompatible in 796ms
Error while waiting for external thread/process
java.io.IOException: User limit of inotify instances reached or too many open files
        at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
        at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
        at net.cardosi.mojo.cache.CachedProject.lambda$null$4(CachedProject.java:229)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
failed org.dominokit.samples:dominodo-j2cl:1.0-SNAPSHOT TranspileSources class java.util.concurrent.CompletionException:java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
        at net.cardosi.mojo.cache.CachedProject.lambda$null$4(CachedProject.java:264)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        ... 3 more
Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
        at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
        at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
        at net.cardosi.mojo.cache.CachedProject.lambda$null$4(CachedProject.java:229)
        ... 4 more
failed org.dominokit.samples:dominodo-j2cl:1.0-SNAPSHOT AssembleOutput-54378f2da51d7c5f4b0ba9db497ce0f4082d3e29 class java.util.concurrent.CompletionException:java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
        at net.cardosi.mojo.cache.CachedProject.lambda$null$4(CachedProject.java:264)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        ... 3 more
Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
        at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
        at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
        at net.cardosi.mojo.cache.CachedProject.lambda$null$4(CachedProject.java:229)
        ... 4 more
```

**Comment by niloc132** [comment]
The important thing here is that we don't want transient OS or filesystem issues to poison the cache and prevent reading those entries again later. 

The specific issue here is that linux limits the number of inotify instances, due to resources they consume, and somehow there were no more available. Presently, we use one watch instance per pending dependency _that may be building in another thread/process_ - these shouldn't last long, there shouldn't be many of them. It might be better to use a single watch service globally (per file system, which probably cannot be more than 2, one for the reactor sources, one for the cache dir), though then we need a little more bookkeeping to tell which change affects what.

A failure here, while trying to detect other failures/successes should be retried or fail in such a way that downstream dependencies don't also fail.

**Comment by niloc132** [comment]
I'm sort of ignoring this issue right now, as it seems like it might have been transient, and something we can revisit another time when we get more reports of it occurring again.
