### ISSUE TITLE
mvn install fails with exception

### ISSUE THREAD

**Issue by FrankHossfeld** [Vertispan/j2clmavenplugin#35]
Trying to run `mvn clean install` on a project fails:
```
[INFO] Reactor Summary for dominodo 1.0-SNAPSHOT:
[INFO] 
[INFO] dominodo ........................................... SUCCESS [  0.109 s]
[INFO] dominodo-shared .................................... SUCCESS [  0.977 s]
[INFO] dominodo-client .................................... SUCCESS [  9.127 s]
[INFO] dominodo-gwt ....................................... SUCCESS [ 28.023 s]
[INFO] dominodo-j2cl ...................................... FAILURE [01:06 min]
[INFO] dominodo-server .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:45 min
[INFO] Finished at: 2020-03-08T19:27:01+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vertispan.j2cl:j2cl-maven-plugin:0.13-SNAPSHOT:build (run-devmode) on project dominodo-j2cl: Execution run-devmode of goal com.vertispan.j2cl:j2cl-maven-plugin:0.13-SNAPSHOT:build failed: java.io.UncheckedIOException: java.nio.file.FileAlreadyExistsException: /Users/hoss/.m2/gwt3-cache-dir/0.13-SNAPSHOT/dominodo-client-c7673cce0843a8da1638b52898d6a2a0765556d4 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
java.io.UncheckedIOException: java.nio.file.FileAlreadyExistsException: /Users/hoss/.m2/gwt3-cache-dir/0.13-SNAPSHOT/dominodo-client-c7673cce0843a8da1638b52898d6a2a0765556d4
	at net.cardosi.mojo.cache.DiskCache.entry(DiskCache.java:59)
	at net.cardosi.mojo.cache.CachedProject.lambda$hash$33(CachedProject.java:651)
	at net.cardosi.mojo.cache.CachedProject.lambda$null$7(CachedProject.java:313)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.FileAlreadyExistsException: /Users/hoss/.m2/gwt3-cache-dir/0.13-SNAPSHOT/dominodo-client-c7673cce0843a8da1638b52898d6a2a0765556d4
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at net.cardosi.mojo.cache.DiskCache.entry(DiskCache.java:57)
	... 8 more
```
The exception occurs, while updating the dominodo example to the latest plugin & elemento version.

**Comment by niloc132** [comment]
This is apparently hard to reproduce, appears that it is caused by a race condition in creating the directory. I switches two sites that were creating a directory to instead permit the directory to already exist - for at least those two operations, we don't care if we created it so long as it is created.

If someone runs into this (or something like this) again, please reopen with a stack trace.
