### ISSUE TITLE
java.nio.file.FileSystemNotFoundException for gwt-internal-annotations

### ISSUE THREAD

**Issue by niloc132** [Vertispan/j2clmavenplugin#46]
```
java.nio.file.FileSystemNotFoundException: /home/colin/.m2/repository/com/vertispan/j2cl/gwt-internal-annotations/0.4-SNAPSHOT/gwt-internal-annotations-0.4-SNAPSHOT.jar
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at net.cardosi.mojo.cache.CachedProject.lambda$hash$33(CachedProject.java:640)
```

I've seen this error or one like it a few times, tracking here.

**Comment by niloc132** [comment]
Now seen also as 
```
java.nio.file.FileSystemNotFoundException: /home/colin/.m2/repository/org/gwtproject/core/gwt-core/1.0-SNAPSHOT/gwt-core-1.0-SNAPSHOT.jar
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at net.cardosi.mojo.cache.CachedProject.lambda$hash$50(CachedProject.java:916)
	at net.cardosi.mojo.cache.CachedProject.lambda$null$9(CachedProject.java:333)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It looks like this happens when a transitive dependency requires one of its dependencies, even though the root project has no use for it - maven won't fetch it automatically, we need to ask it to do so when resolving that project.
